In [9]:
import pandas as pd
import os
from skimage import io
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, precision_score, recall_score, classification_report, f1_score, roc_auc_score
import pickle
import Functions2
from sklearn.linear_model import LogisticRegression as LR
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, classification_report

In [10]:
# Load the data
data_path = r'C:\Users\serru\OneDrive\Documents\Project2\Project-2-Medical-Imaging\data\ColorMask\Training'
df = pd.read_csv(data_path)

# Preprocess the diagnostic column
df['diagnostic'] = df['diagnostic'].map({'BCC': 1, 'MEL': 1, 'SCC': 1, 'ACK': 0, 'NEV': 0, 'SEK': 0})

# Define the function to extract features
def extract_features(folder_path):
    feature_1 = []
    feature_2 = []
    feature_3 = []
    feature_4 = []
    feature_5 = []
    feature_6 = []
    feature_7 = []

    for filename in os.listdir(folder_path):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            image_path = os.path.join(folder_path, filename)
            original = io.imread(image_path)

            # Ignore the alpha channel (e.g. transparency)
            if original.shape[-1] == 4:
                original = original[..., :3]

            feature_1.append(Functions2.measure_pigment_network(original))
            feature_2.append(Functions2.measure_blue_veil(original))
            feature_3.append(Functions2.measure_vascular(original))
            feature_4.append(Functions2.measure_globules(original))
            feature_5.append(Functions2.measure_streaks(original))
            feature_6.append(Functions2.measure_irregular_pigmentation(original))
            feature_7.append(Functions2.measure_regression(original))

    return feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7

# Define the folder path for image processing
folder_path_in = r'C:\Users\serru\OneDrive\Documents\Project2\Project-2-Medical-Imaging\data\full_data.csv'

# Extract features from the images
feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7 = extract_features(folder_path_in)

# Create a DataFrame for the features
features_df = pd.DataFrame()
features_df["img_id"] = [filename for filename in os.listdir(folder_path_in) if filename.endswith(('.jpg', '.png'))]
features_df["1: pigment network"] = feature_1
features_df["2: Blue veil"] = feature_2
features_df["3: Vascular"] = feature_3
features_df["4: Globules"] = feature_4
features_df["5: Streaks"] = feature_5
features_df["6: Pigmentation"] = feature_6
features_df["7: Regression"] = feature_7

# Merge the features DataFrame with the diagnostic column from the original DataFrame
df_merged2 = pd.merge(df[['img_id', 'diagnostic']], features_df, on='img_id', how='inner')



PermissionError: [Errno 13] Permission denied: 'C:\\Users\\serru\\OneDrive\\Documents\\Project2\\Project-2-Medical-Imaging\\data\\ColorMask\\Training'

In [ ]:
df_merged = df_merged2

In [ ]:

data_path = r"/Users/bogdancristianmihaila/Desktop/2nd Semester/Github/project2/Project-2-Medical-Imaging/data/helpme/newdata.csv"
df = pd.read_csv(data_path)

new_df = pd.DataFrame()
new_df['img_id'] = df['image']
new_df['diagnostic'] = df[['MEL', 'BCC', 'AKIEC']].any(axis=1).astype(int)
df = new_df

In [ ]:
# Define the function to extract features
def extract_features(folder_path):
    feature_1 = []
    feature_2 = []
    feature_3 = []
    feature_4 = []
    feature_5 = []
    feature_6 = []
    feature_7 = []

    for filename in os.listdir(folder_path):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            image_path = os.path.join(folder_path, filename)
            original = io.imread(image_path)

            # Ignore the alpha channel (e.g. transparency)
            if original.shape[-1] == 4:
                original = original[..., :3]

            feature_1.append(Functions2.measure_pigment_network(original))
            feature_2.append(Functions2.measure_blue_veil(original))
            feature_3.append(Functions2.measure_vascular(original))
            feature_4.append(Functions2.measure_globules(original))
            feature_5.append(Functions2.measure_streaks(original))
            feature_6.append(Functions2.measure_irregular_pigmentation(original))
            feature_7.append(Functions2.measure_regression(original))

    return feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7

In [ ]:
# Define the folder path for image processing
folder_path_in = r"/Users/bogdancristianmihaila/Desktop/2nd Semester/Github/project2/Project-2-Medical-Imaging/data/both_resized"

# Extract features from the images
feature_1, feature_2, feature_3, feature_4, feature_5, feature_6, feature_7 = extract_features(folder_path_in)

In [ ]:
# Create a DataFrame for the features
features_df = pd.DataFrame()
features_df["img_id"] = [filename for filename in os.listdir(folder_path_in) if filename.endswith(('.jpg', '.png'))]
features_df["1: pigment network"] = feature_1
features_df["2: Blue veil"] = feature_2
features_df["3: Vascular"] = feature_3
features_df["4: Globules"] = feature_4
features_df["5: Streaks"] = feature_5
features_df["6: Pigmentation"] = feature_6
features_df["7: Regression"] = feature_7

# Merge the features DataFrame with the diagnostic column from the original DataFrame
df_merged = pd.merge(df[['img_id', 'diagnostic']], features_df, on='img_id', how='inner')

In [ ]:
features_df['img_id'] = features_df['img_id'].str.replace('.jpg', '')

df_merged = pd.merge(df[['img_id', 'diagnostic']], features_df, on='img_id', how='inner')

In [ ]:
#add the 2 datasets one under the other
df_merged = pd.concat([df_merged, df_merged2], ignore_index=True)
df_merged

NameError: name 'df_merged' is not defined

In [ ]:
# Split the data into training and testing sets
X = df_merged.drop(['img_id', 'diagnostic'], axis=1)
Y = df_merged['diagnostic']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5)

In [ ]:
df_merged

NameError: name 'df_merged' is not defined

### Training classifiers without PCA

In [ ]:
import numpy as np
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score, confusion_matrix, precision_score, recall_score, accuracy_score

classifiers = [LR(), KNN(), DTC()]  # Replace with your trained classifiers

# Perform cross-validation for each classifier
for classifier in classifiers:
    y_pred = cross_val_predict(classifier, X, Y, cv=5)  # Change cv value as per your requirement
    
    # Calculate evaluation metrics
    f1 = f1_score(Y, y_pred)
    precision = precision_score(Y, y_pred)
    recall = recall_score(Y, y_pred)
    tn, fp, fn, tp = confusion_matrix(Y, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    print(f"Classifier: {type(classifier).__name__}")
    print(f"F1 score: {f1}")
    print(f"Precision: {precision}")
    print(f"Recall/Sensitivity: {recall}")
    print(f"Specificity: {specificity}")
    print("Confusion Matrix:")
    print(confusion_matrix(Y, y_pred))
    print()


Classifier: LogisticRegression
F1 score: 0.8974358974358974
Precision: 0.8641975308641975
Recall/Sensitivity: 0.9333333333333333
Specificity: 0.65625
Confusion Matrix:
[[21 11]
 [ 5 70]]

Classifier: KNeighborsClassifier
F1 score: 0.8227848101265823
Precision: 0.7831325301204819
Recall/Sensitivity: 0.8666666666666667
Specificity: 0.4375
Confusion Matrix:
[[14 18]
 [10 65]]

Classifier: DecisionTreeClassifier
F1 score: 0.7272727272727272
Precision: 0.7647058823529411
Recall/Sensitivity: 0.6933333333333334
Specificity: 0.5
Confusion Matrix:
[[16 16]
 [23 52]]



### Training classifiers with PCA

In [ ]:
# import numpy as np
# from sklearn.model_selection import cross_val_predict
# from sklearn.metrics import f1_score, confusion_matrix, precision_score, recall_score
# from sklearn.decomposition import PCA

# classifiers = [LR(), KNN(), DTC()]  # Replace with your trained classifiers

# # Perform PCA
# pca = PCA(0.95)  # Adjust the number of components as per your requirement
# X_pca = pca.fit_transform(X)

# # Perform cross-validation for each classifier
# for classifier in classifiers:
#     y_pred = cross_val_predict(classifier, X_pca, Y, cv=5)  # Change cv value as per your requirement
    
#     # Calculate evaluation metrics
#     f1 = f1_score(Y, y_pred)
#     precision = precision_score(Y, y_pred)
#     recall = recall_score(Y, y_pred)
#     tn, fp, fn, tp = confusion_matrix(Y, y_pred).ravel()
#     specificity = tn / (tn + fp)
    
#     print(f"Classifier: {type(classifier).__name__}")
#     print(f"F1 score: {f1}")
#     print(f"Precision: {precision}")
#     print(f"Recall/Sensitivity: {recall}")
#     print(f"Specificity: {specificity}")
#     print("Confusion Matrix:")
#     print(confusion_matrix(Y, y_pred))
#     print()

Classifier: LogisticRegression
F1 score: 0.6072874493927125
Precision: 0.635593220338983
Recall/Sensitivity: 0.5813953488372093
Specificity: 0.49411764705882355
Confusion Matrix:
[[42 43]
 [54 75]]

Classifier: KNeighborsClassifier
F1 score: 0.654275092936803
Precision: 0.6285714285714286
Recall/Sensitivity: 0.6821705426356589
Specificity: 0.38823529411764707
Confusion Matrix:
[[33 52]
 [41 88]]

Classifier: DecisionTreeClassifier
F1 score: 0.6463878326996197
Precision: 0.6343283582089553
Recall/Sensitivity: 0.6589147286821705
Specificity: 0.4235294117647059
Confusion Matrix:
[[36 49]
 [44 85]]



***Saving the models***

In [ ]:
# import pickle

# # In the path where you want to save the models
# path = r'/Users/bogdancristianmihaila/Desktop/2nd Semester/Github/project2/Project-2-Medical-Imaging/Pickle/final_pickles'

# # Save the models
# #pickle.dump(LR, open(path + r'/LR_good.pkl', 'wb'))
# pickle.dump(KNN, open(path + r'/KNN_bad.pkl', 'wb'))
# #pickle.dump(DTC, open(path + r'\DTC.pkl', 'wb'))



In [ ]:
from joblib import dump
dump(LR, 'LR_good.joblib')

['LR_good.joblib']